package uk.gov.moj.cpp.support.queryapi.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Query - Rule for finding feedback by dates or case ids"
  when
    $outcome: Outcome();
    $action: Action(name == "support.find-feedback");
    eval(userAndGroupProvider.isSystemUser($action));
  then
    $outcome.setSuccess(true);
end


