package uk.gov.moj.cpp.support.command.api.accesscontrol;

import uk.gov.moj.cpp.accesscontrol.drools.Outcome;
import uk.gov.moj.cpp.accesscontrol.drools.Action;

import uk.gov.moj.cpp.support.command.api.accesscontrol.RuleConstants;

global uk.gov.moj.cpp.accesscontrol.common.providers.UserAndGroupProvider userAndGroupProvider;

rule "Command - Rule for sending feedback comment"
  when
    $outcome: Outcome();
    $action: Action(name == "support.command.api.send-feedback");
    eval(userAndGroupProvider.isMemberOfAnyOfTheSuppliedGroups($action, RuleConstants.getSendFeedbackGroup()));
  then
    $outcome.setSuccess(true);
end
